<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SunDirectionAppInstaller</AssemblyName>
    <ApplicationIcon>..\assets\sun-direction-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\dist\SunDirectionApp.zip" LogicalName="SunDirectionApp.zip" />
  </ItemGroup>
</Project>